type: "simulstream.server.speech_processors.seamless_sliding_window_retranslation.SeamlessSlidingWindowRetranslator"
hf_model_name: "facebook/seamless-m4t-v2-large"
seamless_version: 2
detokenizer_type: "hf"
window_len: 12
lang_tag_template: "__{}__"
matching_threshold: 0.1