hostname: localhost
port: 8080
secure: false
speech_processing_frequency: 2.0  # seconds

metrics:
  enabled: True
  filename: "metrics.jsonl"

webui:
  model_name: SeamlessM4T
  tgt_supported_langs:
    - eng: "ğŸ‡¬ğŸ‡§ English"
    - ita: "ğŸ‡®ğŸ‡¹ Italian"
  src_supported_langs:
    - eng: "ğŸ‡¬ğŸ‡§ English"
    - ita: "ğŸ‡®ğŸ‡¹ Italian"
